# Generated by Django 4.2.1 on 2023-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawca',
            name='grupa_krwi',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('0+', '0+'), ('0-', '0-')], max_length=3),
        ),
    ]
