# Generated by Django 4.2.1 on 2023-06-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_alter_dawca_grupa_krwi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dawca',
            old_name='adres',
            new_name='adres_mailowy',
        ),
        migrations.RemoveField(
            model_name='dawca',
            name='czynnik_Rh',
        ),
    ]
