# Generated by Django 4.2.1 on 2023-06-10 19:48

import aplikacja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_rename_adres_dawca_adres_mailowy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawca',
            name='adres_mailowy',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dawca',
            name='data_urodzenia',
            field=models.DateField(validators=[aplikacja.models.validate_data_urodzenia]),
        ),
        migrations.AlterField(
            model_name='dawca',
            name='numer_telefonu',
            field=models.CharField(max_length=20, validators=[aplikacja.models.validate_telefon]),
        ),
    ]
