# Generated by Django 4.2.1 on 2023-06-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_alter_dawca_adres_mailowy_alter_dawca_data_urodzenia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterField(
            model_name='transfuzja',
            name='data_transfuzji',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='grupa_krwi',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('0+', '0+'), ('0-', '0-')], default='A+', max_length=3),
        ),
    ]
