# Generated by Django 4.2.4 on 2024-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0006_opinia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='opinia',
            name='data',
        ),
        migrations.AddField(
            model_name='opinia',
            name='stacja',
            field=models.CharField(default='Gdańsk', max_length=100),
            preserve_default=False,
        ),
    ]
